routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('user', 'UserController');
Route::resource('role', 'RoleController');
Route::resource('permission', 'PermissionController')->except(['show']);
Route::get('permission/init','PermissionController@init')->name('permission.init');
//Route::any('role/set/{role}', 'RoleController@set')->name('role.set');
Route::match(['get', 'post'],'role/set/{role}','RoleController@set')->name('role.set');
Route::match(['get', 'post'],'user/set/{user}','UserController@set')->name('user.set');
Route::match(['get', 'post'],'user/reset-password/{user}','UserController@resetPassword')->name('user.reset-password');

app/Models/Permission.php
<?php

namespace SepCMS\Models;

use Spatie\Permission\Models\Permission as BasicPermission;
use Auth,Log;

class Permission extends BasicPermission
{
    protected $table = 'permissions';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name','display_name', 'guard_name', 'icon', 'is_menu', 'status', 'parent_id',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
    ];

    public  $_config = [
        'channel'           => '权限管理',
        'title'             => '权限',
        'keywords'          => '账户维护',
        'description'       => '账户信息维护，设置角色、状态启用或禁用以及新建',
        'router'            => '/account/ability',           //路由
        'controller'        => 'Account\AbilityController',  //控制器
        'filter'            => true,                         //列表页是否开启条件搜索
        'pageSize'          => 20,                           //页面长度
        'orderBy'           => 'id',                         //排序字段
        'orderMethod'       => 'desc',                       //排序方式
        'templateIndex'     => 'account.ability.GetIndex',       //列表页模板
        'templateEdit'      => 'template.GetEdit',       //编辑、新建页模板
        'templateShow'      => 'template.GetShow',        //展示页模板
        'routeNamePrefix'   => 'ability',                 //路由名称前缀, 使用公共列别模板，该项必须配置
        'items'             => [
            'display_name' => [
                'title'     => '权限名称',
                'filter'    => true,
                'type'      => 'text',
                'validator' => 'required|max:50'
            ],
            'path_name'    => [
                'title'  => '路由名称',
                'filter' => true,
                'type'   => 'text',
            ],
            'class'    => [        //字段名称
                'title'  => '类名称',  //字段描述
                'filter' => false,        //是否做为列表页的筛选条件
                'type'   => 'text',  //编辑页控件类型
                'hidden' => false,       //列表页是否显示
            ],
            'is_menu'    => [          //字段名称
                'title'  => '菜单',   //字段描述
                'filter' => true,     //是否做为列表页的筛选条件
                'type'   => 'radio',  //编辑页控件类型
                'hidden' => false,    //列表页是否显示
                'selectItems' => [
                    '1'  => '是',
                    '0'  => '否',
                ],
            ],
            'sort'    => [
                'title'  => '排序',
                'filter' => true,
                'type'   => 'text',
            ],
            'status'    => [          //字段名称
                'title'  => '状态',   //字段描述
                'filter' => true,     //是否做为列表页的筛选条件
                'type'   => 'radio',  //编辑页控件类型
                'hidden' => false,    //列表页是否显示
                'selectItems' => [
                    '1'  => '启用',
                    '0'  => '禁用',
                ],
            ],
            'parent_id'    => [          //字段名称
                'title'  => '父级名称',   //字段描述
                'filter' => false,     //是否做为列表页的筛选条件
                'type'   => 'select',  //编辑页控件类型
                'hidden' => false,    //列表页是否显示
            ],
            'created_at'    => [          //字段名称
                'title'  => '创建时间',   //字段描述
                'filter' => false,     //是否做为列表页的筛选条件
                'type'   => 'text',  //编辑页控件类型
                'hidden' => false,    //列表页是否显示
            ],
            'updated_at'    => [          //字段名称
                'title'  => '更新时间',   //字段描述
                'filter' => false,     //是否做为列表页的筛选条件
                'type'   => 'text',  //编辑页控件类型
                'hidden' => false,    //列表页是否显示
            ],
        ],
    ];

    /**
     * @todo    获取模型基础配置
     *
     * @author  Justin.W<justin.bj@msn.com>
     * @return  mixed
     */
    public function getConfig()
    {
        $parents = self::where('is_menu','1')->where('status','1')->get();
        $parents = array_pluck($parents,'display_name','id');
        array_set($this->_config,'items.parent_id.selectItems',$parents);
        return $this->_config;
        return $this->_config;
    }

    /**
     * @todo 获取权限列表，按照级别递归结果
     *
     * @author Justin.W<justin.bj@msn.com>
     *
     * @param  int    $parent_id 父级id
     * @param  string $is_menu   标示 1 menu，0 all
     * @param  mixed  $existAbilities
     * @return mixed
     */
    public function menus()
    {
        $menus         = [];
        $abilities     = Auth::user()->getAllPermissions();

        if($abilities)
        {
            $abilitySet = array_filter($abilities->toArray(), function($val){
                return $val['is_menu'] === "1" ? true: false;
            });

            recursion($abilitySet,$menus);
        }
        return $menus;
    }

    public function parent()
    {
        return $this->hasOne('App\Models\Ability','id','parent_id');
    }

}

app/Http/Controllers/PermissionController.php
<?php

namespace SepCMS\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use SepCMS\Logic\Basic;
use SepCMS\Models\Permission;
use Route, DB;

class PermissionController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @param  Request $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $object = [
            'title' => '控制面板',
            'url'   => '/home',
        ];

        $data           = $request->all();
        $data['object'] = $object;
        $data['permissions']  = Permission::paginate(config('paginate.page_size'));
        return view('permission.index', $data);
    }

    public function create(Request $request)
    {
        $data = $request->all();
        return view('permission.edit', $data);
    }

    public function edit(Permission $permission)
    {
        $object = [
            'title' => '控制面板',
            'url'   => '/home',
        ];
        $data['permission']  = $permission;
        $data['object']      = $object;
        return view('permission.edit', $data);
    }

    public function update(Permission $permission, Request $request)
    {
        $data = $request->all();
        if ($permission->update($data)){
            $request->session()->flash('message', '更新成功');
            return Redirect::route('permission.index',[$permission]);
        } else {
            $request->session()->flash('message', '更新失败，请重试');
            return Redirect::route('permission.edit',[$permission]);
        }
    }

    public function store(Permission $permission, Request $request)
    {

    }

    public function destroy(Permission $permission)
    {

    }

    public function show(Permission $permission)
    {

    }

    public function init()
    {
        //list all route name
        $routes = [];
        foreach (Route::getRoutes()->getRoutes() as $item){
            if (!starts_with($item->uri,'api') && $item->getName() && Basic::isAuthorization($item->getActionName())) {
                array_push($routes, $item->getName());
            }
        }

        $permissions = Permission::all();
        $exists      = [];
        foreach ($permissions as $item){
            if(!in_array($item->name, $routes)){
                $item->delete();
            } else {
                array_push($exists, $item->name);
            }
        }

        $news      = [];
        foreach($routes as $key => $val) {
            if (!in_array($val, $exists)) {
                array_push($news, $val);
            }
        }

        $abilities = [];
        if ($news) {
            foreach ($news as $index => $ability) {
                array_push($abilities,[
                    'name'       => $ability,
                    'guard_name' => 'web',
                    'status'     => '1',
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ]);
            }

            DB::table('permissions')->insert($abilities);
        }

        request()->session()->flash('message','权限已经成功索引');
        return Redirect::route('permission.index');
    }
}

resources/views/permission/edit.blade.php
@extends('layouts.admin')

@section('top-menu')
    {{ Breadcrumbs::render('home', $object) }}
@endsection
@section('content')
    <div class="row">
        <div class="col-xs-12">
            <div class="box box-info">
                <div class="box-header with-border">
                    <h3 class="box-title">编辑权限信息</h3>
                </div>
                @if(Session::has('message'))
                    <div class="alert alert-success alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <h4><i class="icon fa fa-check"></i> {{ Session::get('message') }}</h4>

                    </div>
                @endif

                <!-- /.box-header -->
                <!-- form start -->
                <form class="form-horizontal" action="{{route('permission.update', [$permission->id])}}" method="post">
                    <input type="hidden" name="_token" value="{{ csrf_token() }}" />
                    <input hidden="hidden" name="_method" value="put" />
                    <input hidden="id" name="id" value="{{$permission->id}}" />
                    <div class="box-body">
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">路由名称</label>

                            <div class="col-sm-5">
                                <input type="text" class="form-control" id="name" name="name" placeholder="Route Name" value="{{ $permission->name }}">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputPassword3" class="col-sm-2 control-label">Guard Name</label>

                            <div class="col-sm-5">
                                <input type="text" class="form-control" id="guard_name" name="guard_name" placeholder="Guard Name" value="{{ $permission->guard_name }}">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">权限名称</label>

                            <div class="col-sm-5">
                                <input type="text" class="form-control" id="display_name" name="display_name" placeholder="Display Name" value="{{ $permission->display_name }}">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputPassword3" class="col-sm-2 control-label">图标</label>

                            <div class="col-sm-5">
                                <input type="text" class="form-control" id="icon" name="icon" placeholder="ICON" value="{{ $permission->icon }}">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">菜单</label>

                            <div class="col-sm-5">
                                <div class="radio">
                                    <label>
                                        <input type="radio" name="is_menu" id="is_menu" value="1" @if($permission->is_menu == '1') checked="checked" @endif> 是
                                    </label>

                                    <label class="col-sm-offset-1">
                                        <input type="radio" name="is_menu" id="is_menu" value="0" @if(empty($permission->is_menu)) checked="checked" @endif> 否
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputPassword3" class="col-sm-2 control-label">上级菜单编号</label>

                            <div class="col-sm-5">
                                <input type="text" class="form-control" id="parent_id" name="parent_id" placeholder="Parent Menu ID" value="{{ $permission->parent_id }}">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">状态</label>

                            <div class="col-sm-5">
                                <div class="radio">
                                    <label>
                                        <input type="radio" name="status" id="status" value="1" @if($permission->status == '1') checked="checked" @endif> 启用
                                    </label>

                                    <label class="col-sm-offset-1">
                                        <input type="radio" name="status" id="status" value="0" @if(empty($permission->status)) checked="checked" @endif> 禁用
                                    </label>
                                </div>
                            </div>
                        </div>

                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer">
                        <div class="pull-right">
                            <button type="submit" class="btn btn-info">保存</button>
                            <button type="button" class="btn btn-default">返回</button>
                        </div>
                    </div>
                    <!-- /.box-footer -->
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/permission/index.blade.php
@extends('layouts.admin')

@section("css")
  <!-- DataTables -->
  <link rel="stylesheet" href="/resource/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">
@endsection

@section('top-menu')
    {{ Breadcrumbs::render('system', $object) }}
@endsection
@section('content')
    <div class="row">
        <div class="col-xs-12">
            <div class="box box-info">
                <div class="box-header">
                    <h3 class="box-title">权限列表</h3>
                    <div class="pull-right box-tools">
                        <a href="{{route('permission.init')}}">
                            <button type="button" class="btn btn-block btn-info">更新权限</button>
                        </a>
                    </div>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    @if(Session::has('message'))
                    <div class="alert alert-success alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <h4><i class="icon fa fa-check"></i> {{ Session::get('message') }}</h4>

                    </div>
                    @endif

                    <table id="example2" class="table table-bordered table-hover">
                        <thead>
                            <tr>
                                <th>序号</th>
                                <th>权限</th>
                                <th>ICON</th>
                                <th>GUARD</th>
                                <th>显示名称</th>
                                <th>父级名称</th>
                                <th>菜单</th>
                                <th>状态</th>
                                <th>创建时间</th>
                                <th>更新时间</th>
                                <th>操作</th>
                            </tr>
                        </thead>
                        @if($permissions->count())
                        <tbody>
                            @foreach($permissions as $permission)
                            <tr>
                                <td>{{ $permission->id }}</td>
                                <td>{{ $permission->name }}</td>
                                <td>@if(!empty($permission->icon))<i class="{{ $permission->icon }}"></i>@else - @endif</td>
                                <td>{{ $permission->guard_name }}</td>
                                <td>{{ $permission->display_name }}</td>
                                <td>{{ $permission->parent_id }}</td>
                                <td>{{ $permission->is_menu }}</td>
                                <td>{{ $permission->status }}</td>
                                <td>{{ $permission->created_at }}</td>
                                <td>{{ $permission->updated_at }}</td>
                                <td>
                                    <a href="{{route('permission.edit',[$permission->id])}}">编辑</a>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                        @endif
                    </table>
                        {{$permissions->links()}}
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
      <!-- /.row -->

@endsection


@section("js")
<!-- DataTables -->
<script src="/resource/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
<script src="/resource/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>

@endsection