routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('user', 'UserController');
Route::resource('role', 'RoleController');
Route::resource('permission', 'PermissionController')->except(['show']);
Route::get('permission/init','PermissionController@init')->name('permission.init');
//Route::any('role/set/{role}', 'RoleController@set')->name('role.set');
Route::match(['get', 'post'],'role/set/{role}','RoleController@set')->name('role.set');
Route::match(['get', 'post'],'user/set/{user}','UserController@set')->name('user.set');
Route::match(['get', 'post'],'user/reset-password/{user}','UserController@resetPassword')->name('user.reset-password');

app/Models/Role.php
<?php

namespace SepCMS\Models;

use Spatie\Permission\Models\Role as BasicRole;

class Role extends BasicRole
{

    protected $table = 'roles';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'guard_name',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
    ];

    public  $_config = [

    ];

    /**
     * @todo    获取模型基础配置
     *
     * @author  Justin.W<justin.bj@msn.com>
     * @return  mixed
     */
    public function getConfig()
    {
        return $this->_config;
    }

    public function abilities()
    {
        return $this->belongsToMany('App\Models\Ability')->withTimestamps();
    }
}

app/Http/Controllers/RoleController.php
<?php

namespace SepCMS\Http\Controllers;

use Illuminate\Http\Request;
use SepCMS\Models\Permission;
use SepCMS\Models\Role;
use Illuminate\Support\Facades\Redirect;

class RoleController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @param  $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $object = [
            'title' => '控制面板',
            'url'   => '/home',
        ];

        $data           = $request->all();
        $data['object'] = $object;
        $data['roles']  = Role::all();
        return view('role.index', $data);
    }

    public function create(Request $request)
    {
        $object = [
            'title' => '控制面板',
            'url'   => '/home',
        ];
        $data           = $request->all();
        $data['object'] = $object;
        return view('role.create', $data);
    }

    public function edit(Role $role)
    {
        $object = [
            'title' => '控制面板',
            'url'   => '/home',
        ];
        $data['role']        = $role;
        $data['object']      = $object;
        return view('role.edit', $data);
    }

    public function update(Role $role, Request $request)
    {
        $data = $request->all();
        if($role->update($data)){
            request()->session()->flash('message','角色更新成功');
            return Redirect::route('role.index');
        } else {
            request()->session()->flash('message','角色更新失败');
            return Redirect::route('role.edit', [$role->id]);
        }
    }

    public function store( Request $request)
    {
        $role = new Role();
        $data = $request->all();
        $role->name = $request->get('name');
        $role->guard_name = $request->get('guard_name');
        if ($role->save($data)) {
            request()->session()->flash('message','角色创建成功');
            return Redirect::route('role.index');
        } else {
            request()->session()->flash('message','角色创建失败');
            return Redirect::route('role.create');
        }
    }

    public function destroy(Role $role)
    {
        if ($role->delete()){
            request()->session()->flash('message','角色删除成功');
        } else {
            request()->session()->flash('message','角色删除失败');
        }

        return Redirect::route('role.index');
    }

    public function set(Role $role, Request $request)
    {
        $object = [
            'title' => '控制面板',
            'url'   => '/home',
        ];

        if($request->method() == 'POST' ) {
            $permissions = $request->get('permissions');
            if ($permissions) {
                $permissionsOBJ = [];
                foreach($permissions as $key => $permission) {
                    $permissionsOBJ[] = Permission::findById($permission);
                }

                if ($role->syncPermissions($permissionsOBJ)) {
                    request()->session()->flash('message','分配权限成功');
                } else {
                    request()->session()->flash('message','分配权限失败');
                }
            } else {
                request()->session()->flash('message', '请选择权限');
            }

        }

        $permissions       = new Permission();
        $abilities         = $permissions->menus();
        $data['abilities'] = $abilities;
        $data['role']      = $role;
        $data['object']    = $object;
        return view('role.set', $data );
    }


}

resources/views/role/create.blade.php
@extends('layouts.admin')

@section('top-menu')
    {{ Breadcrumbs::render('home', $object) }}
@endsection
@section('content')
    <div class="row">
        <div class="col-xs-12">
            <div class="box box-info">
                <div class="box-header with-border">
                    <h3 class="box-title">编辑角色信息</h3>
                </div>
                @if(Session::has('message'))
                    <div class="alert alert-success alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <h4><i class="icon fa fa-check"></i> {{ Session::get('message') }}</h4>

                    </div>
                @endif

                <!-- /.box-header -->
                <!-- form start -->
                <form class="form-horizontal" action="{{route('role.store')}}" method="post">
                    <input type="hidden" name="_token" value="{{ csrf_token() }}" method="post" />
                    <div class="box-body">
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">角色名称</label>

                            <div class="col-sm-5">
                                <input type="text" class="form-control" id="name" name="name" placeholder="Route Name" value="{{ old('name') }}">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputPassword3" class="col-sm-2 control-label">Guard Name</label>

                            <div class="col-sm-5">
                                <input type="text" class="form-control" id="guard_name" name="guard_name" placeholder="Guard Name" value="{{ old('guard_name') }}">
                            </div>
                        </div>
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer">
                        <div class="pull-right">
                            <button type="submit" class="btn btn-info">保存</button>
                            <button type="button" class="btn btn-default">返回</button>
                        </div>
                    </div>
                    <!-- /.box-footer -->
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/role/edit.blade.php
@extends('layouts.admin')

@section('top-menu')
    {{ Breadcrumbs::render('home', $object) }}
@endsection
@section('content')
    <div class="row">
        <div class="col-xs-12">
            <div class="box box-info">
                <div class="box-header with-border">
                    <h3 class="box-title">编辑角色信息</h3>
                </div>
                @if(Session::has('message'))
                    <div class="alert alert-success alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <h4><i class="icon fa fa-check"></i> {{ Session::get('message') }}</h4>

                    </div>
                @endif

                <!-- /.box-header -->
                <!-- form start -->
                <form class="form-horizontal" action="{{route('role.update', [$role->id])}}" method="post">
                    <input type="hidden" name="_token" value="{{ csrf_token() }}" />
                    <input hidden="hidden" name="_method" value="put" />
                    <input hidden="id" name="id" value="{{$role->id}}" />
                    <div class="box-body">
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">角色名称</label>

                            <div class="col-sm-5">
                                <input type="text" class="form-control" id="name" name="name" placeholder="Route Name" value="{{ $role->name }}">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputPassword3" class="col-sm-2 control-label">Guard Name</label>

                            <div class="col-sm-5">
                                <input type="text" class="form-control" id="guard_name" name="guard_name" placeholder="Guard Name" value="{{ $role->guard_name }}">
                            </div>
                        </div>
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer">
                        <div class="pull-right">
                            <button type="submit" class="btn btn-info">保存</button>
                            <a href="{{route("role.index")}}" class="btn btn-default">返回</a>
                        </div>
                    </div>
                    <!-- /.box-footer -->
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/role/index.blade.php
@extends('layouts.admin')

@section("css")
  <!-- DataTables -->
  <link rel="stylesheet" href="/resource/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">
@endsection

@section('top-menu')
    {{ Breadcrumbs::render('system', $object) }}
@endsection
@section('content')
    <div class="row">
        <div class="col-xs-12">
          <div class="box">
            <div class="box-header">
                <h3 class="box-title">角色列表</h3>
                <div class="pull-right">
                    <a class="btn btn-sm btn-success" href="{{ route('role.create') }}">创建角色</a>
                </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                @if(Session::has('message'))
                    <div class="alert alert-success alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <h4><i class="icon fa fa-check"></i> {{ Session::get('message') }}</h4>
                    </div>
                @endif
                <table id="example2" class="table table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>序号</th>
                            <th>角色名称</th>
                            <th>GUARD</th>
                            <th>创建时间</th>
                            <th>更新时间</th>
                            <th>操作</th>
                        </tr>
                    </thead>
                    @if($roles->count())
                    <tbody>
                    @foreach($roles as $role)
                        <tr>
                            <td>{{ $role->id }}</td>
                            <td>{{ $role->name }}</td>
                            <td>{{ $role->guard_name }}</td>
                            <td>{{ $role->created_at }}</td>
                            <td>{{ $role->updated_at }}</td>
                            <td>
                                <a href="{{ route('role.set', [$role]) }}">分配权限</a>
                                <a href="{{route('role.edit', [$role])}}">编辑</a>
                                <form action="{{ route('role.destroy', [$role->id]) }}" method="POST" style="display: inline">
                                    {{ csrf_field() }}{{ method_field('DELETE') }}
                                    <a href="javascript:void(0);" class="btn-delete" >删除</a>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                    @endif
                </table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->

@endsection


@section("js")
<!-- DataTables -->
<script src="/resource/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
<script src="/resource/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>

@endsection

resources/views/role/set.blade.php
@extends('layouts.admin')

@section('top-menu')
    {{ Breadcrumbs::render('home', $object) }}
@endsection
@section('content')
    <div class="row">
        <div class="col-xs-12">
            <div class="box box-info">
                <div class="box-header with-border">
                    <h3 class="box-title">{{ $role->name }}维护权限信息</h3>
                </div>
                @if(Session::has('message'))
                    <div class="alert alert-success alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <h4><i class="icon fa fa-check"></i> {{ Session::get('message') }}</h4>

                    </div>
                @endif

                <!-- /.box-header -->
                <!-- form start -->
                <div class="box-body">
                <form class="form-horizontal" action="{{route('role.set', [$role->id])}}" method="post">
                    <input type="hidden" name="_token" value="{{ csrf_token() }}" />
                    <div id="menu-tree" class="box-body checkbox">
                        <ul style="list-style-type:none;">
                            @foreach($abilities as $key => $first)
                            <li style="list-style-type:none; ">
                                <a href="#">
                                    <label>
                                        <input type="checkbox" data-role="checkbox" name="permissions[]" @if($role->hasPermissionTo($first['name'])) checked @endif value="{{$first['id']}}">
                                        <span>{{$first['display_name'] ? : $first['name']}}</span>
                                    </label>
                                    @if(isset($first['sub_list']) && count($first['sub_list']))
                                    <span class="pull-right-container">
                                        <i class="fa fa-angle-left pull-right"></i>
                                    </span>
                                    @endif
                                </a>
                                @if(isset($first['sub_list']) && count($first['sub_list']))
                                <ul style="list-style-type:none;display: block;">
                                    @foreach($first['sub_list'] as $i => $second)
                                    <li style="list-style-type:none;">
                                        <a href="#">
                                            <label>
                                                <input type="checkbox" name="permissions[]" @if($role->hasPermissionTo($second['name'])) checked @endif  value="{{$second['id']}}"> {{$second['display_name'] ? : $second['name']}}
                                            </label>
                                            @if(isset($second['sub_list']) && count($second['sub_list']))
                                            <span class="pull-right-container">
                                                <i class="fa fa-angle-left pull-right"></i>
                                            </span>
                                            @endif
                                        </a>
                                        @if(isset($second['sub_list']) && count($second['sub_list']))
                                        <ul style="list-style-type:none;">
                                            @foreach($second['sub_list'] as $ii => $third)
                                            <li style="list-style-type:none;">
                                                <a href="#">
                                                    <label>
                                                        <input type="checkbox" name="permissions[]" @if($role->hasPermissionTo($third['name'])) checked @endif value="{{$third['id']}}"> {{$third['display_name'] ? : $third['name']}}
                                                    </label>
                                                    @if(isset($third['sub_list']) && count($third['sub_list']))
                                                    <span class="pull-right-container">
                                                        <i class="fa fa-angle-left pull-right"></i>
                                                    </span>
                                                    @endif
                                                </a>
                                                @if(isset($third['sub_list']) && count($third['sub_list']))
                                                <ol style="list-style-type:none;">
                                                    @foreach($third['sub_list'] as $iii => $four)
                                                    <li>
                                                        <a href="{{action($four['name'])}}">
                                                            <label>
                                                                <input type="checkbox" name="permissions[]" @if($role->hasPermissionTo($four['name'])) checked @endif value="{{$four['id']}}"> {{$four['display_name'] ? : $four['name']}}
                                                            </label>
                                                        </a>
                                                    </li>
                                                    @endforeach
                                                </ol>
                                                @endif
                                            </li>
                                            @endforeach
                                        </ul>
                                        @endif
                                    </li>
                                    @endforeach
                                </ul>
                                @endif
                            </li>
                            @endforeach
                        </ul>
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer">
                        <div class="pull-right">
                            <button type="submit" class="btn btn-info">保存</button>
                            <a href="{{route("role.index")}}" class="btn btn-default">返回</a>
                        </div>
                    </div>
                    <!-- /.box-footer -->
                </form>

                </div>
            </div>
        </div>
    </div>
@endsection

@section('js')
<script text="">
    function menuTreeInit(id)
    {
        $("#menu-tree ui")
    }

    $("#menu-tree")
</script>
@endsection