routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('user', 'UserController');
Route::resource('role', 'RoleController');
Route::resource('permission', 'PermissionController')->except(['show']);
Route::get('permission/init','PermissionController@init')->name('permission.init');
//Route::any('role/set/{role}', 'RoleController@set')->name('role.set');
Route::match(['get', 'post'],'role/set/{role}','RoleController@set')->name('role.set');
Route::match(['get', 'post'],'user/set/{user}','UserController@set')->name('user.set');
Route::match(['get', 'post'],'user/reset-password/{user}','UserController@resetPassword')->name('user.reset-password');

app/Models/User.php
<?php

namespace SepCMS\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace SepCMS\Http\Controllers;

use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;
use SepCMS\Models\Role;
use SepCMS\Models\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $object = [
            'title' => '控制面板',
            'url' => '/home',
        ];

        $data['object'] = $object;
        $data['users'] = User::all();
        return view('user.index', $data);
    }

    public function create()
    {
        $data = [];
        return view('user.edit', $data);
    }

    public function edit(User $user, Request $request)
    {

    }

    public function update(User $user, Request $request)
    {

    }

    public function store(User $user, Request $request)
    {

    }

    public function destroy(User $user)
    {
        if ($user->delete()) {
            request()->session()->flash('message', '用户删除成功');
        } else {
            request()->session()->flash('message', '用户删除失败');
        }

        return Redirect::route('user.index');
    }

    public function set(User $user, Request $request)
    {
        $object = [
            'title' => '控制面板',
            'url' => '/home',
        ];

        if ($request->method() == 'POST') {
            $roles = $request->get('roles');
            if ($roles) {
                $rolesOBJ = [];
                foreach ($roles as $key => $role) {
                    $rolesOBJ[] = Role::findById($role);
                }

                if ($user->syncRoles($rolesOBJ)) {
                    request()->session()->flash('message', '分配权限成功');
                } else {
                    request()->session()->flash('message', '分配权限失败');
                }
            } else {
                request()->session()->flash('message', '请选择权限');
            }

        }

        $data['roles'] = Role::all();
        $data['user'] = $user;
        $data['object'] = $object;
        return view('user.set', $data);
    }

    public function resetPassword(User $user, Request $request)
    {
        $object = [
            'title' => '控制面板',
            'url' => '/home',
        ];

        if ($request->method() == 'POST') {

            $verification = Validator::make($request->all(), [
                'password'    => 'required|alpha_dash|between:6,12',
                're-password' => 'same:password',
            ])->validate();
            if (!$verification) {
                return redirect('user.reset-password',[$user])->withErrors($verification);
            }
            $user->password = Hash::make($request->get('password'));

            if ($user->save()) {
                request()->session()->flash('message', '重置密码成功');
            } else {
                request()->session()->flash('message', '重置密码失败');
            }

        }

        $data['roles'] = Role::all();
        $data['user'] = $user;
        $data['object'] = $object;
        return view('user.reset-password', $data);
    }
}

resources/views/user/edit.blade.php
@extends('layouts.admin')

@section('top-menu')
    {{ Breadcrumbs::render('home', $object) }}
@endsection
@section('content')
    <div class="row justify-content-center">
        <div class="box col-md-8">
            <div class="card">
                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/user/index.blade.php
@extends('layouts.admin')

@section("css")
  <!-- DataTables -->
  <link rel="stylesheet" href="/resource/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">
@endsection

@section('top-menu')
    {{ Breadcrumbs::render('system', $object) }}
@endsection
@section('content')
    <div class="row">
        <div class="col-xs-12">
          <div class="box">
            <div class="box-header">
              <h3 class="box-title">管理员列表</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table id="example2" class="table table-bordered table-hover">
                <thead>
                <tr>
                    <th>用户名</th>
                    <th>邮箱</th>
                    <th>邮箱状态</th>
                    <th>状态</th>
                    <th>创建时间</th>
                    <th>更新时间</th>
                    <th>操作</th>
                </tr>
                </thead>
                @if($users->count())
                <tbody>
                @foreach($users as $user)
                <tr>
                    <td>{{ $user->name }}</td>
                    <td>{{ $user->email }}</td>
                    <td>{{ $user->verified_at ? '已验证' : '未验证' }}</td>
                    <td>{{ $user->status == 'enable' ? '启用' : '禁用' }}</td>
                    <td>{{ $user->created_at }}</td>
                    <td>{{ $user->updated_at }}</td>
                    <td>
                        <a href="{{route('user.set', [$user->id])}}">分配角色</a>|
                        <a href="{{route('user.reset-password', [$user->id])}}">重置密码</a>|
                        <form action="{{ route('user.destroy', [$user->id]) }}" method="POST" style="display: inline">
                            {{ csrf_field() }}{{ method_field('DELETE') }}
                            <a href="javascript:void(0);" class="btn-delete" >删除</a>
                        </form>
                    </td>
                </tr>
                @endforeach
                <tr>
                </tbody>
                @endif
              </table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->


        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->

@endsection


@section("js")
<!-- DataTables -->
<script src="/resource/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
<script src="/resource/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
<script>
  $(function () {

    $('#example2').DataTable({
      'paging'      : true,
      'lengthChange': false,
      'searching'   : false,
      'ordering'    : true,
      'info'        : true,
      'autoWidth'   : false
    })
  })
</script>
@endsection

resources/views/user/reset-password.blade.php
@extends('layouts.admin')

@section('top-menu')
    {{ Breadcrumbs::render('home', $object) }}
@endsection
@section('content')
    <div class="row">
        <div class="col-xs-12">
            <div class="box box-info">
                <div class="box-header with-border">
                    <h3 class="box-title">重置密码</h3>
                </div>
                @if(Session::has('message'))
                    <div class="alert alert-success alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <h4><i class="icon fa fa-check"></i> {{ Session::get('message') }}</h4>

                    </div>
                @endif

                <!-- /.box-header -->
                <!-- form start -->
                <form class="form-horizontal" action="{{route('user.reset-password', [$user->id])}}" method="post">
                    <input type="hidden" name="_token" value="{{ csrf_token() }}" />
                    <input hidden="id" name="id" value="{{$user->id}}" />
                    <div class="box-body">
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">密码</label>

                            <div class="col-sm-5">
                                <input type="password" class="form-control" id="password" name="password"  value="">
                                {{ $errors->first('password') }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputPassword3" class="col-sm-2 control-label">确认密码</label>
                            <div class="col-sm-5">
                                <input type="password" class="form-control" id="re-password" name="re-password" value="">
                                {{ $errors->first('re-password') }}
                            </div>
                        </div>
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer">
                        <div class="pull-right">
                            <button type="submit" class="btn btn-info">保存</button>
                            <a href="{{route("user.index")}}" class="btn btn-default">返回</a>
                        </div>
                    </div>
                    <!-- /.box-footer -->
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/user/set.blade.php
@extends('layouts.admin')

@section('top-menu')
    {{ Breadcrumbs::render('home', $object) }}
@endsection
@section('content')
    <div class="row">
        <div class="col-xs-12">
            <div class="box box-info">
                <div class="box-header with-border">
                    <h3 class="box-title">{{ $user->name }}维护用户角色信息</h3>
                </div>
                @if(Session::has('message'))
                    <div class="alert alert-success alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <h4><i class="icon fa fa-check"></i> {{ Session::get('message') }}</h4>

                    </div>
                @endif

                <!-- /.box-header -->
                <!-- form start -->
                <div class="box-body">
                <form class="form-horizontal" action="{{route('user.set', [$user->id])}}" method="post">
                    <input type="hidden" name="_token" value="{{ csrf_token() }}" />
                    <div id="menu-tree" class="box-body checkbox">
                        <ul style="list-style-type:none;">
                            @foreach($roles as $key => $role)
                            <li style="list-style-type:none; ">
                                <a href="#">
                                    <label>
                                        <input type="checkbox" data-role="checkbox" name="roles[]" @if($user->hasRole($role->name)) checked @endif value="{{$role->id}}">
                                        <span>{{$role->name}}</span>
                                    </label>
                                </a>
                            </li>
                            @endforeach
                        </ul>
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer">
                        <div class="pull-right">
                            <button type="submit" class="btn btn-info">保存</button>
                            <a href="{{route("user.index")}}" class="btn btn-default">返回</a>
                        </div>
                    </div>
                    <!-- /.box-footer -->
                </form>

                </div>
            </div>
        </div>
    </div>
@endsection

@section('js')
<script text="">
    function menuTreeInit(id)
    {
        $("#menu-tree ui")
    }

    $("#menu-tree")
</script>
@endsection